### ISSUE TITLE
Consider splitting time picker in hours and minutes

### ISSUE THREAD

**Issue by adrianboimvaser** [xdan/datetimepicker#4]
When the step is small (say: 15 or 10) it's kinda annoying scrolling to find a time.

**Comment by vyshkant** [comment]
Я, если честно, так и не понял: была реализована возможность выбирать не только часы, но и минуты? Или отказались от этой идеи?

**Comment by xdan** [comment]
отказался. то была лишь идея

**Comment by JD0909** [comment]
is there possible to get time slots like 00:00, 00:30.. and upto... 23:30 , 24:00

**Comment by deepika1203** [comment]
How to achieve this style, hours and minutes in separate fields?

**Comment by Bert-de-Jong** [comment]
For those who found this thread.
The developer of this repository has since created commercial plugins that allow separation of hours and minutes, namely [TimePicker](https://xdsoft.net/jqplugins/timepicker/) and, with date, [Calendar Popup](https://xdsoft.net/jqplugins/calendar-popup/).
Some other options can be found in the lists [here](https://github.com/search?o=desc&q=timepicker&s=stars&type=Repositories), [here](https://plugins.jquery.com/tag/timepicker/) and [here](https://www.jqueryscript.net/tags.php?/Time%20Picker/).
Personally, I settled with Flatpickr, but everyone will have their own preferences.
