### ISSUE TITLE
Deleting selected values from the datepicker

### ISSUE THREAD

**Issue by DanCardin** [xdan/datetimepicker#416]
If you select more than 1 character on the datepicker's input text field, the code here: https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.js#L2171 just subtracts 1 from the position and replaces that with a '_'. 

I think this should be doing something, where it checks the selectionStart/selectionEnd before running, and either batch deleting everything in between, or repeatedly reapplying the existing character-replacing logic for the length of the selection.

Something like the below maybe(?), which is a modified version of that section of code, which sort of does the right thing with selections, but pretty much does the wrong thing in a lot of no-selection situations

```
input.on('keydown.xdsoft', function (event) {
  var val = this.value,
    key = event.which,
    selectionLength = this.selectionEnd - this.selectionStart,
    pos = this.selectionStart,
    digit;

  if (((key >= KEY0 && key <= KEY9) || (key >= _KEY0 && key <= _KEY9)) || (key === BACKSPACE || key === DEL)) {
    digit = (key !== BACKSPACE && key !== DEL) ? String.fromCharCode((_KEY0 <= key && key <= _KEY9) ? key - KEY0 : key) : '_';

    if ((key === BACKSPACE || key === DEL) && pos) {
      pos += 1;
      digit = '_';
    }

    while (selectionLength > 0) {
      while (/[^0-9_]/.test(options.mask.substr(pos, 1)) && pos < options.mask.length && pos > 0) {
       pos += 1;//(key === BACKSPACE || key === DEL) ? -1 : 1;
       selectionLength -= 1;
      }

      val = val.substr(0, pos) + digit + val.substr(pos + 1);
      if ($.trim(val) === '') {
        val = options.mask.replace(/[0-9]/g, '_');
      } else {
        if (pos === options.mask.length) {
          event.preventDefault();
          return false;
        }
      }

      pos += 1;//(key === BACKSPACE || key === DEL) ? 0 : 1;
      while (/[^0-9_]/.test(options.mask.substr(pos, 1)) && pos < options.mask.length && pos > 0) {
        pos += 1;//(key === BACKSPACE || key === DEL) ? -1 : 1;
        selectionLength -= 1;
      }

      selectionLength -= 1;
    }
```

**Comment by KyleMit** [comment]
Here's a Minimal, Complete, and Verifiable example which  showcases the problems deleting text when the [mask][option.mask] option is set to `true`

### [MCVE in Plunker][plunk mcve]


### Problem 1 - <kbd>Backspace</kbd> with selection only deletes first character

![del sel][del sel]

### Problem 2 - <kbd>Del</kbd> key deletes previous char, not next char

![del key][del key]

The root of the problem occurs inside of the [`'keydown.xdsoft'` handler on line 2,267][2267]

Specifically, on [the following line which builds the new value][2286]:

```js
val = val.substr(0, pos) + digit + val.substr(pos + 1);
```

Here's the same thing with broken up into lots of steps with descriptive variable names:

```js
var valueBeforeCurPos = val.substr(0, pos);
var currentCharToInsert = digit;
var valueAfterCurPos = val.substr(pos + 1);
var newValue = valueBeforeCurPos + currentCharToInsert + valueAfterCurPos;
val = newValue // set new val
```

This  will grab everything before the current cursor position, add the newly built character (either input or blank placeholder `_`), and then add everything after the current position plus one. So it will only replace a single character at a time.  However, if there is a selection, the normal UX expectation is that everything currently selected will be cleared upon deleting or typing a new char

Which can be accomplished like this:

```js
var selectionLength = this.selectionEnd - this.selectionStart;
var defaultBlank = options.mask.replace(/[0-9]/g, '_');
var valueBeforeCurSel = val.substr(0, pos);
var currentCharToInsert = digit;

var defaultCharsForSelectionLength = defaultBlank.substr(pos + 1, selectionLength -1); // could be empty if only one char selected

var charsAfterSelection = val.substr(pos + 1 + selectionLength);
var newValue = valueBeforeCurSel + currentCharToInsert + defaultCharsForSelectionLength + charsAfterSelection
val = newValue // set new val
```

Which grabs the selection information via [`.selectionStart`][selectionStart] and [`.selectionEnd`][selectionEnd] which should be [compatible across all major browsers][caniuse input-selection]






For problem 2, the other problematic code is in treating `BACKSPACE` and `DEL` as identical directions.  At least on a windows machine, these have different meanings.

This appears in several places inside the handler on lines [2,277][2277], [2,283][2283], [2,297][2297], and [2,299][2299]

```js
pos += (key === BACKSPACE || key === DEL) ? -1 : 1;
```

The solution is that really for del we can treat it as a forward facing type action, almost similar to <kbd>insert</kbd> being on where we are actively replacing the next character with the default placeholder for that position (`_`).  So with respect to changing position, the only thing that should decrement is the BACKSPACE Key)

### [Here's a Working Demo in Plunker with the updates outline above applied][plunk fixed]

Because this method uses a lot of local functions, there's no easy way to apply an independent patch on top of the library after it loads, so if you want to fix now, you might have to settle for forking a copy and applying the fix inside the library itself.

For long term maintainability, I'll put together a pull request so it can be incorporated into the main build, but until that point here's a rewrite for the keydown event handler function:

```js
input.on('keydown.xdsoft', function (event) {
	var val = this.value,
		key = event.which,
		selectionLength = this.selectionEnd - this.selectionStart, 
		pos,
		digit;

	// only alow these characters
	if (((key >=  KEY0 && key <=  KEY9)  ||
		 (key >= _KEY0 && key <= _KEY9)) || 
		 (key === BACKSPACE || key === DEL)) {
		   
	    // get init position    
	    pos = getCaretPos(this);
		
	    // get char to insert which is character or placeholder ('_')
	    digit = (key === BACKSPACE || key === DEL) ? '_' :
				  String.fromCharCode((_KEY0 <= key && key <= _KEY9) ? key - KEY0 : key);

		// we're deleting something
		if (key === BACKSPACE && pos) {
			pos -= 1;
			// if we have a selection length, cursor actually sits behind deletable char, not in front
			if (selectionLength>0) pos += 1;
		}
		
		
		// value char - keep incrementing position while on separator char and we still have room
		// del  char - keep decrementing position while on separator char and we still have room
		
		
		// // don't stop on a separator, continue whatever direction you were going
		while (true) {
		  var maskValueAtCurPos = options.mask.substr(pos, 1);
		  var posShorterThanMaskLength = pos < options.mask.length;
		  var posGreaterThanZero = pos > 0;
		  var notNumberOrPlaceholder = /[^0-9_]/;
		  var shiftPosition = notNumberOrPlaceholder.test(maskValueAtCurPos) && posShorterThanMaskLength && posGreaterThanZero
		  
		  // if we hit a real char, stay where we are
		  if (!shiftPosition) break;
			
		  pos += (key === BACKSPACE) ? -1 : 1;
							
		}
		
		// if we have a selection length we will wipe out entire selection and replace with default template for that range
		var defaultBlank = options.mask.replace(/[0-9]/g, '_');
		var valueBeforeCurSel = val.substr(0, pos);
		var nextCharToInsert = digit;
		var defaultCharsForSelectionLength = defaultBlank.substr(pos + 1, selectionLength -1); // could be empty if only one char selected
		var charsAfterSelection = val.substr(pos + 1 + selectionLength);
		val = valueBeforeCurSel + nextCharToInsert + defaultCharsForSelectionLength + charsAfterSelection


		if ($.trim(val) === '') {
		  // if empty, set to default
			val = defaultBlank
		} else {
		  // if at the last character don't need to do anything
			if (pos === options.mask.length) {
				event.preventDefault();
				return false;
			}
		}

		// resume cursor location
		pos += (key === BACKSPACE || key === DEL) ? 0 : 1;
		// don't stop on a separator, continue whatever direction you were going
		while (/[^0-9_]/.test(options.mask.substr(pos, 1)) && pos < options.mask.length && pos > 0) {
			pos += (key === BACKSPACE || key === DEL) ? -1 : 1;
		}
	
		if (isValidValue(options.mask, val)) {
			this.value = val;
			setCaretPos(this, pos);
		} else if ($.trim(val) === '') {
			this.value = options.mask.replace(/[0-9]/g, '_');
		} else {
			input.trigger('error_input.xdsoft');
		}
	} else {
		if (([AKEY, CKEY, VKEY, ZKEY, YKEY].indexOf(key) !== -1 && ctrlDown) || [ESC, ARROWUP, ARROWDOWN, ARROWLEFT, ARROWRIGHT, F5, CTRLKEY, TAB, ENTER].indexOf(key) !== -1) {
			return true;
		}
	}
	
	event.preventDefault();
	return false;
});
```

[del sel]: https://user-images.githubusercontent.com/4307307/33944742-ffb17642-dfea-11e7-9b66-855a0cd9854d.gif
[del key]: https://user-images.githubusercontent.com/4307307/33944757-08774a90-dfeb-11e7-9e0c-3a13c3fac27b.gif

[plunk mcve]: https://plnkr.co/edit/1pA8PCDwGqKkoIFUIU2t?p=preview
[plunk fixed]: https://plnkr.co/edit/yiPxQJatQAFBUEswXBzr?p=preview

[option.mask]: https://xdsoft.net/jqplugins/datetimepicker/#mask

[2267]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2267
[2286]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2286
[2277]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2277
[2283]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2283
[2297]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2297
[2299]: https://github.com/xdan/datetimepicker/blob/2.5.14/jquery.datetimepicker.js#L2299

[selectionStart]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Property/selectionStart
[selectionEnd]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Property/selectionEnd
[caniuse input-selection]: https://caniuse.com/#feat=input-selection

**Comment by KyleMit** [comment]
Also added a way to handle paste operations

```js
input.on('paste.xdsoft', function (event) {
  // couple options here
  // 1. return false - tell them they can't paste
  // 2. insert over current characters - minimal validation
  // 3. full fledged parsing and validation
  // let's go option 2 for now

  // fires multiple times for some reason

  // https://stackoverflow.com/a/30496488/1366033
  var clipboardData = event.clipboardData || event.originalEvent.clipboardData || window.clipboardData,
      pastedData = clipboardData.getData('text'),
      val = this.value,
      pos = this.selectionStart

  var valueBeforeCursor = val.substr(0, pos);
  var valueAfterPaste = val.substr(pos + pastedData.length);

  val = valueBeforeCursor + pastedData + valueAfterPaste;           
  pos += pastedData.length;

  if (isValidValue(options.mask, val)) {
    this.value = val;
    setCaretPos(this, pos);
  } else if ($.trim(val) === '') {
    this.value = options.mask.replace(/[0-9]/g, '_');
  } else {
    input.trigger('error_input.xdsoft');
  }

  event.preventDefault();
  return false;
});
```
